name: Deploy

on:
  push:
    branches: [ main ]

jobs:   
  deploy_to_dev:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - uses: actions/checkout@v2
      - name: CF CLI Action
        uses: citizen-of-planet-earth/cf-cli-action@v2
        with:
          cf_api: https://api.london.cloud.service.gov.uk
          cf_username: ${{ secrets.CF_USER }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: dfe-digital
          cf_space: academy-transfers-prototype
          command: set-env academy-transfers-prototype-api SomeKey SomeValue && set-env academy-transfers-prototype-api AnotherKey AnotherValue
